# Copyright (C) 2008-2015, Marvell International Ltd.
# All Rights Reserved.

exec-y += aws_sensor_demo
aws_sensor_demo-objs-y :=  src/main.c src/adc.c src/aws_main.c
# Applications could also define custom board files if required using following:
#adc_demo-board-y := /path/to/boardfile
